name: Build Docker e Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Construir a imagem Docker
        run: docker build -t minha-pagina-nginx .

      - name: Verificar se a imagem foi criada
        run: docker images minha-pagina-nginx

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Fazer upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
